id: A6B460E00
title: Toh_97-The_Chapter_on_Manjusri%E2%80%99s_Magical_Display-v1
type: translation
pechas:
- ICE91D669
- IE1EB52A9
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-046-003
  eft-text-version: 1.1.4 2021
  title: Toh_97-The_Chapter_on_Manjusri%E2%80%99s_Magical_Display-v1
alignment_to_base:
  ICE91D669/E787: 49C1
  IE1EB52A9/F116: 49C1
